# Generated by Django 3.1.2 on 2020-10-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team', models.CharField(max_length=5)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('team',),
            },
        ),
    ]
