# Generated by Django 3.1.2 on 2020-10-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstatsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('time', models.CharField(max_length=15)),
                ('pointsGenerated', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBAstatsApp.team')),
            ],
        ),
    ]
