# Generated by Django 3.1.2 on 2020-10-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstatsApp', '0002_assist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('ot', models.IntegerField()),
                ('awayPoints', models.IntegerField()),
                ('homePoints', models.IntegerField()),
                ('awayFTM', models.IntegerField()),
                ('homeFTM', models.IntegerField()),
                ('awayFTA', models.IntegerField()),
                ('homeFTA', models.IntegerField()),
                ('awayFGM', models.IntegerField()),
                ('homeFGM', models.IntegerField()),
                ('awayFGA', models.IntegerField()),
                ('homeFGA', models.IntegerField()),
                ('away3PM', models.IntegerField()),
                ('home3PM', models.IntegerField()),
                ('awayAssists', models.IntegerField()),
                ('homeAssists', models.IntegerField()),
                ('awayTurnovers', models.IntegerField()),
                ('homeTurnovers', models.IntegerField()),
                ('awaySteals', models.IntegerField()),
                ('homeSteals', models.IntegerField()),
                ('awayBlocks', models.IntegerField()),
                ('homeBlocks', models.IntegerField()),
                ('awayRebounds', models.IntegerField()),
                ('homeRebounds', models.IntegerField()),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='NBAstatsApp.team')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='NBAstatsApp.team')),
            ],
        ),
        migrations.AlterField(
            model_name='assist',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBAstatsApp.match'),
        ),
        migrations.AlterUniqueTogether(
            name='assist',
            unique_together={('code', 'time')},
        ),
    ]
