# Generated by Django 3.1.2 on 2020-10-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstatsApp', '0003_auto_20201027_1731'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assist',
            unique_together=set(),
        ),
    ]
