# Generated by Django 3.1.2 on 2020-10-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstatsApp', '0004_auto_20201028_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assist',
            name='pointsGenerated',
        ),
        migrations.RemoveField(
            model_name='assist',
            name='team',
        ),
        migrations.RemoveField(
            model_name='assist',
            name='time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away3PM',
        ),
        migrations.RemoveField(
            model_name='match',
            name='awayAssists',
        ),
        migrations.RemoveField(
            model_name='match',
            name='awayBlocks',
        ),
        migrations.RemoveField(
            model_name='match',
            name='awayFGA',
        ),
        migrations.RemoveField(
            model_name='match',
            name='awayFGM',
        ),
        migrations.RemoveField(
            model_name='match',
            name='awayFTA',
        ),
        migrations.RemoveField(
            model_name='match',
            name='awayFTM',
        ),
        migrations.RemoveField(
            model_name='match',
            name='awayPoints',
        ),
        migrations.RemoveField(
            model_name='match',
            name='awayRebounds',
        ),
        migrations.RemoveField(
            model_name='match',
            name='awaySteals',
        ),
        migrations.RemoveField(
            model_name='match',
            name='awayTurnovers',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home3PM',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homeAssists',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homeBlocks',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homeFGA',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homeFGM',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homeFTA',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homeFTM',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homePoints',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homeRebounds',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homeSteals',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homeTurnovers',
        ),
        migrations.AddField(
            model_name='assist',
            name='data',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='match',
            name='data',
            field=models.JSONField(default=[]),
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(default=[])),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBAstatsApp.match')),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(default=[])),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBAstatsApp.match')),
            ],
        ),
        migrations.CreateModel(
            name='Steal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(default=[])),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBAstatsApp.match')),
            ],
        ),
        migrations.CreateModel(
            name='Rebound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(default=[])),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBAstatsApp.match')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(default=[])),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBAstatsApp.match')),
            ],
        ),
        migrations.CreateModel(
            name='Foul',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(default=[])),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBAstatsApp.match')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(default=[])),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBAstatsApp.match')),
            ],
        ),
    ]
