# Generated by Django 3.1.2 on 2020-11-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstatsApp', '0006_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
