# Generated by Django 3.1.2 on 2021-01-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstatsApp', '0009_standings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
