# Generated by Django 3.1.2 on 2021-01-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstatsApp', '0010_auto_20210119_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Standings',
            new_name='Standing',
        ),
    ]
