# Generated by Django 3.1.2 on 2021-02-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBAstatsApp', '0012_auto_20210119_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('receipt', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
